### ISSUE TITLE
Installation error relating to ffmpeg

### ISSUE THREAD

**Issue by jyjd99** [expyriment/expyriment#132]
Hello, I am new to expyriment.

I am using mac sierra and installed both python2/3. 
I followed installation guide on the expyriment website through both default and alternative way. 

When I import expyriment, I have an error message for both python versions relating to ffmpeg. 
I have an internet access and error message told me I should report. 

For python2: 
Imageio: 'ffmpeg.osx' was not found on your computer; downloading it now.

Error while fetching file: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>.

Error while fetching file: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>.

Error while fetching file: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>.

Error while fetching file: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>.

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/expyriment/__init__.py", line 115, in <module>

    stimuli.Video.get_ffmpeg_binary()  # in case it needs to be downloaded

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/expyriment/stimuli/_video.py", line 76, in get_ffmpeg_binary

    imageio.plugins.ffmpeg.download()

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 55, in download

    get_remote_file('ffmpeg/' + FNAME_PER_PLATFORM[plat])

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/imageio/core/fetching.py", line 121, in get_remote_file

    _fetch_file(url, filename)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/imageio/core/fetching.py", line 177, in _fetch_file

    os.path.basename(file_name))

IOError: Unable to download 'ffmpeg.osx'. Perhaps there is a no internet connection? If there is, please report this problem.

For python3:

Imageio: 'ffmpeg.osx' was not found on your computer; downloading it now.

Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>.

Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>.

Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>.

Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)>.

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 82, in get_exe

    auto=False)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/core/fetching.py", line 102, in get_remote_file

    raise NeedDownloadError()

imageio.core.fetching.NeedDownloadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/expyriment/stimuli/_video.py", line 70, in get_ffmpeg_binary

    ffmpeg_binary = imageio.plugins.ffmpeg.get_exe()

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 86, in get_exe

    raise NeedDownloadError('Need ffmpeg exe. '

imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling:

  imageio.plugins.ffmpeg.download()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/expyriment/__init__.py", line 115, in <module>

    stimuli.Video.get_ffmpeg_binary()  # in case it needs to be downloaded

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/expyriment/stimuli/_video.py", line 76, in get_ffmpeg_binary

    imageio.plugins.ffmpeg.download()

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 55, in download

    get_remote_file('ffmpeg/' + FNAME_PER_PLATFORM[plat])

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/core/fetching.py", line 121, in get_remote_file

    _fetch_file(url, filename)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/imageio/core/fetching.py", line 177, in _fetch_file

    os.path.basename(file_name))

OSError: Unable to download 'ffmpeg.osx'. Perhaps there is a no internet connection? If there is, please report this problem.

I am looking forward to hearing from you. 

Thank you for reading. 

Sincerely, 

YJ

**Comment by fladd** [comment]
Hi there,

this particular issue seems to be related to a too old OpenSSL verison: https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version

Could you check if this solves the issue?

**Comment by fladd** [comment]
The problem is that you misspelled "Experiment".
