### ISSUE TITLE
python setup.py install crash on fresh Ubuntu 22.04 install 

### ISSUE THREAD

**Issue by chrplr** [expyriment/expyriment#197]
First attempt at installing expyriment on Ubuntu 22.04 using the system's python3

```
$ python setup.py install 
/usr/lib/python3/dist-packages/setuptools/dist.py:507: UserWarning: The version specified ('0.10.0-40-g4f47628') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/home/cp983411/tmp/expyriment/setup.py", line 357, in <module>
    run()
  File "/home/cp983411/tmp/expyriment/setup.py", line 306, in run
    setup(name='expyriment',
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 983, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 858, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 172, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python3.10/distutils/cmd.py", line 62, in __init__
    self.initialize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 40, in initialize_options
    orig.install.initialize_options(self)
  File "/usr/lib/python3.10/_distutils_system_mod.py", line 33, in initialize_options
    super().initialize_options()
TypeError: super(type, obj): obj must be an instance or subtype of type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cp983411/tmp/expyriment/setup.py", line 360, in <module>
    raise RuntimeError("Building/Installing Expyriment failed!")
RuntimeError: Building/Installing Expyriment failed!
```

(Note: in another attempt: pip install expyriment crashed trying to compile pygame1.9)

**Comment by chrplr** [comment]
From the deprecation warning from setuptools I have learned that the correct way is now to run: 

    pip install .
    
 from the root dir of the source package (the one containing the setup.py)

Still, the issue is still present: 
 ---
         File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 40, in initialize_options
          orig.install.initialize_options(self)
        File "/usr/lib/python3.10/_distutils_system_mod.py", line 33, in initialize_options
          super().initialize_options()
      TypeError: super(type, obj): obj must be an instance or subtype of type
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/cp983411/tmp/expyriment/setup.py", line 360, in <module>
          raise RuntimeError("Building/Installing Expyriment failed!")
      RuntimeError: Building/Installing Expyriment failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> exp
 ---
 
 Note: To check whether it was problem with my local pip/setuptools, I tried to "compile" other python packages with `pip install .` or `python setup.py install`. It worked.

**Comment by chrplr** [comment]
The issue seems to be linked to setuptools (different errors with different versions...)
