### ISSUE TITLE
Crash Expyriment 0.11.dev1 (prerelease) under Linux

### ISSUE THREAD

**Issue by chrplr** [expyriment/expyriment#217]
Hello,

Testing the prerelease expyriment0.11.dev1 on a linux laptop (with Python 3.12)
The installation (using the pip install line @  <https://github.com/expyriment/expyriment/releases/tag/v0.11.0.dev1>) 
went smoothly, but it crashes as soon as `expyriment.control.initialize` is called: 

```
Expyriment 0.11.dev1 (Python 3.12.0) 
Main file: sound-detection.py (972002)
*** DEVELOP MODE ***
dict_keys([<class 'OpenGL.arrays.ctypesarrays.c_uint_Array_1'>, <class 'bytes'>, <class 'OpenGL.arrays.ctypesarrays.c_double_Array_4_Array_4'>, <class 'OpenGL.arrays.ctypesarrays.c_int_Array_4'>])
Traceback (most recent call last):
  File "/home/cp983411/00_git/PCBS/experiments/xpy_sound_detection/sound-detection.py", line 25, in <module>
    expyriment.control.initialize(exp)
  File "/home/cp983411/.pyenv/versions/expyriment0.11.0dev1/lib/python3.12/site-packages/expyriment/control/_experiment_control.py", line 495, in initialize
    canvas.preload(True)
  File "/home/cp983411/.pyenv/versions/expyriment0.11.0dev1/lib/python3.12/site-packages/expyriment/stimuli/_visual.py", line 1068, in preload
    self._ogl_screen = _LaminaPanelSurface(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/cp983411/.pyenv/versions/expyriment0.11.0dev1/lib/python3.12/site-packages/expyriment/stimuli/_visual.py", line 79, in __init__
    self.refresh_position()
  File "/home/cp983411/.pyenv/versions/expyriment0.11.0dev1/lib/python3.12/site-packages/expyriment/stimuli/_visual.py", line 109, in refresh_position
    bottomleft = oglu.gluUnProject(screensize[0] // 2 - \
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cp983411/.pyenv/versions/expyriment0.11.0dev1/lib/python3.12/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cp983411/.pyenv/versions/expyriment0.11.0dev1/lib/python3.12/site-packages/OpenGL/GLU/projection.py", line 55, in gluUnProject
    result = baseFunction( 
             ^^^^^^^^^^^^^
ctypes.ArgumentError: argument 7: TypeError: No array-type handler for type _ctypes.CArgObject (value: <cparam 'P' (0x74815ff272a0)>) registered
```

**Comment by chrplr** [comment]
After seeing <https://discuss.python.org/t/ctypes-changes-in-py3-12-around-pointers-and-arrays-arguments/35959> ,
I reinstalled expyriment 0.11dev1 in a Python 3.10.12 environment and there was no issue (expyriment ran fine)

**Comment by fladd** [comment]
Mmh, I got the same under Windows, but only with PyOpenGL 3.1.7. This is why I pinned the PyOpenGL requirements to <3.1.7 (because it worked with 3.1.6). Are you saying that you experience this error on Linux also with PyOpenGL 3.1.6 now?

**Comment by fladd** [comment]
Related PyOpenGL bug: https://github.com/mcfletch/pyopengl/issues/99. This seems fixed (since almost a year now), but there has not been a new release that includes that fix. Looking at the PyOpenGL release history, I am not confident that a new release will show up within the next months/years...

**Comment by chrplr** [comment]
>  Are you saying that you experience this error on Linux also with PyOpenGL 3.1.6 now?
Yes. the issue occurs with Python 3.12, but not with 3.10 (both using opengl 3.1.6)

 ```
Python 3.12.0 (main, Dec  7 2023, 17:39:28) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.24.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import expyriment
Expyriment 0.11.dev1 (Python 3.12.0) 

In [2]: import OpenGL

In [3]: OpenGL.__version__
Out[3]: '3.1.6'

```

**Comment by fladd** [comment]
Okay, I attempted to patch PyOpenGL on the fly. Can you pull the master branch and try again (haven't released this as a dev snapshot yet).

**Comment by chrplr** [comment]
Yes! It works now. Bravo !

--
Christophe Pallier

**Comment by fladd** [comment]
Nice!
