### ISSUE TITLE
An experiment can't be unpaused

### ISSUE THREAD

**Issue by Dannnno** [expyriment/expyriment#61]
I'm running the simon task example found [here](http://docs.expyriment.org/Examples.html#simon-task).  I haven't made any modifications to the code.  When I press <kbd>p</kbd> it pauses, as expected.  When I press any other key after this I get this error

```none
Traceback (most recent call last):
  File "C:\Users\dannnno\Desktop\pymem\\Expyriments\Simon_Task\simon_task.py", line 47, in <module>
    control.start()
  File "C:\Users\dannnno\Desktop\pymem\WinPython-32bit-2.7.6.4\python-2.7.6\lib\site-packages\expyriment\control\_experiment_control.py", line 219, in start
    experiment.keyboard.wait()
  File "C:\Users\dannnno\Desktop\pymem\WinPython-32bit-2.7.6.4\python-2.7.6\lib\site-packages\expyriment\io\_keyboard.py", line 215, in wait
    if check_for_control_keys and Keyboard.process_control_keys(event):
  File "C:\Users\dannnno\Desktop\pymem\WinPython-32bit-2.7.6.4\python-2.7.6\lib\site-packages\expyriment\io\_keyboard.py", line 74, in process_control_keys
    pause_function()
  File "C:\Users\dannnno\Desktop\pymem\WinPython-32bit-2.7.6.4\python-2.7.6\lib\site-packages\expyriment\control\_experiment_control.py", line 261, in pause
    return key
NameError: global name 'key' is not defined
```

I took a peek at the source code and saw that it has a seemingly pointless `return key` at the end of the function - I grepped through the expyriment package and didn't find any place where the return value was used.  A fix should just be to remove this line.

**Comment by Dannnno** [comment]
It looks like I have an old version of expyriment - the master branch here doesn't have that line.

Sorry for the trouble.
