### ISSUE TITLE
Test Suite crashes on Windows

### ISSUE THREAD

**Issue by chrplr** [expyriment/expyriment#72]
----
[Anaconda2] >python -m expyriment.cli -T
Expyriment 0.8.0 (Python 2.7.11)
Run Test Suite
Traceback (most recent call last):
  File "C:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda2\lib\site-packages\expyriment\cli.py", line 164, in <module>

    expyriment.control.run_test_suite()
  File "C:\Anaconda2\lib\site-packages\expyriment\control\_test_suite.py", line
568, in run_test_suite
    results = expyriment.get_system_info()
  File "C:\Anaconda2\lib\site-packages\expyriment\_get_system_info.py", line 354
, in get_system_info
    expyriment.io.SerialPort.get_available_ports()
  File "C:\Anaconda2\lib\site-packages\expyriment\io\_serialport.py", line 468,
in get_available_ports
    s = serial.Serial(p)
  File "C:\Anaconda2\lib\site-packages\serial\serialwin32.py", line 31, in __ini
t__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\serial\serialutil.py", line 180, in __ini
t__
    self.open()
  File "C:\Anaconda2\lib\site-packages\serial\serialwin32.py", line 47, in open
    if port.upper().startswith('COM') and int(port[3:]) > 8:
AttributeError: 'int' object has no attribute 'upper'
----

**Comment by fladd** [comment]
I ran into the exact same issue myself two days ago.

The reason seems related to the current PIP provided PySerial for Windows.

The solution for now is to download the and install the .exe from [here](https://pypi.python.org/pypi/pyserial).

In the long run, I hope it will resolve itself by PIP having a newer version.

**Comment by fladd** [comment]
See: https://github.com/expyriment/expyriment/issues/74
